[package]
name = "toc_ir"
version = "0.1.0"
authors = ["DropDemBits <r3usrlnd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toc_ast = { path = "../toc_ast" }
toc_core = { path = "../toc_core" }
petgraph = { version = "^0.5", default-features = false, features = ["stable_graph"] }

[dev-dependencies]
toc_frontend = { path = "../toc_frontend" }