[package]
name = "toc_syntax"
version = "0.1.0"
authors = ["DropDemBits <r3usrlnd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Local deps
toc_scanner = { path = "../toc_scanner" }
toc_span = { path = "../toc_span" }
# External deps
rowan = "0.12.2"
num-derive = "^0.3"
num-traits = "0.2"
lexical = { version = "^5.1", features = [ "radix" ] }
thiserror = "1.0"