[package]
name = "toc_reporting"
version = "0.1.0"
authors = ["DropDemBits <r3usrlnd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toc_span = { path = "../toc_span" }

drop_bomb = "0.1.5"
