[package]
name = "toc_frontend"
version = "0.1.0"
authors = ["DropDemBits <r3usrlnd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toc_ast = { path = "../toc_ast" }
toc_core = { path = "../toc_core" }

unicode-segmentation = "^1.0"
strtod = "0.0"
lazy_static = "1.4.0"

[dev-dependencies]
rand = "0.7"
