name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    # TODO: Put on a matrix for testing on Windows
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install minimal stable toolchain with rustfmt
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt
    - name: Setup cache
      uses: Swatinem/rust-cache@v1.2.0

    # Doing the actual work
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check formatting
      run: cargo fmt -- --check
